### PR TITLE
Update to work with next version of ophyd-async

### PR DESCRIPTION
**Pull request by DominicOram**
Update to work with https://github.com/bluesky/ophyd-async/pull/646. Wait for that to be merged + new ophyd-async release before merging this.

Contains fix from https://github.com/DiamondLightSource/dodal/pull/903 so merge that first

### Instructions to reviewer on how to test:
1. Confirm tests still pass

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://diamondlightsource.github.io/dodal/main/reference/device-standards.html)
- [ ] If changing the API for a pre-existing device, ensure that any beamlines using this device have updated their Bluesky plans accordingly
- [ ] Have the connection tests for the relevant beamline(s) been run via `dodal connect ${BEAMLINE}`

### CODE REVIEW

**Comment by stan-dot** [comment]
@DominicOram can we get a specific version number for this please?

**Comment by DominicOram** [comment]
It's whatever the next version of `ophyd-async` will be so I assume `0.8.0

**Review by callumforrester — APPROVED** [review]
LGTM! Thanks

**Review by noemifrisina — APPROVED** [review]
lgtm, thanks

**Pull request merged**
