### PR TITLE
Remove Container Build from CI

### PR DESCRIPTION
**Pull request by callumforrester**
Fixes ongoing issues in CI caused by dependency pinning
Dodal in a container is not used and building conflicts with ophyd-async dependency pinning often, slowing down the merging of some pull requests. This PR removes it, which will hopefully speed things up.

### Instructions to reviewer on how to test:
1. Ensure CI still passes

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://github.com/DiamondLightSource/dodal/wiki/Device-Standards)

### CODE REVIEW

**Comment by DiamondJoseph** [comment]
Should remove the "Run in a Container" page of the docs too if we remove the container build.

Is there a ticket for switching to the Copier template?

**Review by DiamondJoseph — CHANGES_REQUESTED** [review]
Remove the "Run in a Container" user docs too

**Comment by callumforrester** [comment]
Done, can make a ticket for copier

**Comment by DiamondJoseph** [comment]
> Done, can make a ticket for copier

If you could, then we can discuss with MX about whether we want to adopt or not. It should be comparatively simple as already using skeleton

**Comment by DominicOram** [comment]
>Is there a ticket for switching to the Copier template?
https://github.com/DiamondLightSource/dodal/issues/378

**Review by DominicOram — APPROVED** [review]
Looks good to me, thanks!

**Review by DiamondJoseph — APPROVED** [review]

**Pull request merged**
