### PR TITLE
Allow ophyd_async timeout exception to propagate correctly

### LINKED ISSUE #223: Ophyd-async devices give bad error when not able to connect
If I have an ophyd-async device where one of the PVs cannot connect I get the following error when I run the system tests (i.e. through `make_all_devices`):

```
Traceback (most recent call last):
  File "/scratch/ffv81422/hyperion/dodal/tests/system_tests/test_i03_system.py", line 23, in <module>
    make_all_devices(i03)
  File "/scratch/ffv81422/hyperion/dodal/src/dodal/utils.py", line 125, in make_all_devices
    devices: dict[str, AnyDevice] = invoke_factories(factories, **kwargs)
  File "/scratch/ffv81422/hyperion/dodal/src/dodal/utils.py", line 150, in invoke_factories
    devices[dependent_name] = factories[dependent_name](**params, **kwargs)
  File "/scratch/ffv81422/hyperion/dodal/src/dodal/beamlines/i03.py", line 160, in smargon
    return device_instantiation(
  File "/scratch/ffv81422/hyperion/dodal/src/dodal/utils.py", line 98, in wrapper
    return func(*args, **kwds)
  File "/scratch/ffv81422/hyperion/dodal/src/dodal/beamlines/beamline_utils.py", line 105, in device_instantiation
    _wait_for_connection(device_instance, sim=fake)
  File "/scratch/ffv81422/hyperion/dodal/src/dodal/beamlines/beamline_utils.py", line 51, in _wait_for_connection
    call_in_bluesky_event_loop(
  File "/scratch/ffv81422/hyperion/hyperion/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 2649, in call_in_bluesky_event_loop
    return fut.result(timeout=timeout)
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/concurrent/futures/_base.py", line 460, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Device.connect() done, defined at /scratch/ffv81422/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd_async/core/_device/device.py:48> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<wait_for_connection() done, defined at /scratch/ffv81422/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd_async/core/utils.py:26> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[_chain_future.<locals>._call_set_state() at /dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/futures.py:392]>
Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<Device.connect() done, defined at /scratch/ffv81422/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd_async/core/_device/device.py:48> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-27' coro=<Signal.connect() done, defined at /scratch/ffv81422/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd_async/core/_device/_signal/signal.py:59> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-28' coro=<Signal.connect() done, defined at /scratch/ffv81422/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd_async/core/_device/_signal/signal.py:59> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-29' coro=<Signal.connect() done, defined at /scratch/ffv81422/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd_async/core/_device/_signal/signal.py:59> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-30' coro=<Signal.connect() done, defined at /scratch/ffv81422/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd_async/core/_device/_signal/signal.py:59> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-31' coro=<Signal.connect() done, defined at /scratch/ffv81422/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd_async/core/_device/_signal/signal.py:59> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-32' coro=<Signal.connect() done, defined at /scratch/ffv81422/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd_async/core/_device/_signal/signal.py:59> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```

In this case there was a `Motor` that had an incorrect PV. The error has two issues:
* It contains no hint of which signal failed
* It has a bunch of later errors around task not being destroyed that confuse things (less important)

Note this could be an error internal to ophyd-async

## Acceptance Criteria
* The error is better in this case

### PR DESCRIPTION
**Pull request by DiamondJoseph**
Allows timeouts of ophyd_async devices to propagate their newly informative exceptions correctly.
Fixes #223 

### Instructions to reviewer on how to test:
1. Attempt to connect to a device that is not available with/without the change

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://github.com/DiamondLightSource/dodal/wiki/Device-Standards)

### CODE REVIEW

**Comment by DiamondJoseph** [comment]
This was found while running up p38 devices earlier in the week, isolating the change as unrelated to other changes

**Comment by DominicOram** [comment]
Does this close https://github.com/DiamondLightSource/dodal/issues/223?

**Comment by DiamondJoseph** [comment]
Looks like it- I knew of the ophyd_async side but not of the dodal one. 

I will amend the issue. Would you like me to look at the tests?

**Comment by DominicOram** [comment]
> Would you like me to look at the tests?

Please, if you have the time

**Comment by DiamondJoseph** [comment]
For reference, here's the base of the stack on when I make the Mako Driver have a signal that doesn't exist:

2024-03-18T16:29:54.532004253Z ophyd_async.core.utils.NotConnected: 
2024-03-18T16:29:54.532006003Z coros: NotConnected:
2024-03-18T16:29:54.532008018Z     drv: NotConnected:
2024-03-18T16:29:54.532010795Z         trigger_mode: NotConnected:
2024-03-18T16:29:54.532013513Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-04:DET:Algox_RBV
2024-03-18T16:29:54.532016088Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-04:DET:Algox
2024-03-18T16:29:54.532017670Z 
2024-03-18T16:29:54.532019242Z 
2024-03-18T16:29:54.532025090Z ERROR:    Application startup failed. Exiting.

And for a device that doesn't exist (doesn't seem to collect into a "device disconnected")

2024-03-18T16:32:15.944691264Z Traceback (most recent call last):
2024-03-18T16:32:15.944692963Z   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
2024-03-18T16:32:15.944694635Z     async with self.lifespan_context(app) as maybe_state:
2024-03-18T16:32:15.944696335Z   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
2024-03-18T16:32:15.944699996Z     return await anext(self.gen)
2024-03-18T16:32:15.944701738Z            ^^^^^^^^^^^^^^^^^^^^^
2024-03-18T16:32:15.944703448Z   File "/dls_sw/p38/software/blueapi/devices_only/blueapi/src/blueapi/service/main.py", line 64, in lifespan
2024-03-18T16:32:15.944705182Z     setup_handler(config)
2024-03-18T16:32:15.944706886Z   File "/dls_sw/p38/software/blueapi/devices_only/blueapi/src/blueapi/service/main.py", line 48, in setup_handler
2024-03-18T16:32:15.944708596Z     handler.start()
2024-03-18T16:32:15.944710296Z   File "/dls_sw/p38/software/blueapi/devices_only/blueapi/src/blueapi/service/subprocess_handler.py", line 42, in start
2024-03-18T16:32:15.944712015Z     self._subprocess.apply(setup_handler, [self._config])
2024-03-18T16:32:15.944713698Z   File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 360, in apply
2024-03-18T16:32:15.944715362Z     return self.apply_async(func, args, kwds).get()
2024-03-18T16:32:15.944717058Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-18T16:32:15.944718792Z   File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 774, in get
2024-03-18T16:32:15.944720474Z     raise self._value
2024-03-18T16:32:15.944722152Z ophyd_async.core.utils.NotConnected: 
2024-03-18T16:32:15.944723832Z coros: NotConnected:
2024-03-18T16:32:15.944725544Z     drv: NotConnected:
2024-03-18T16:32:15.944727282Z         trigger_mode: NotConnected:
2024-03-18T16:32:15.944728952Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:TriggerMode_RBV
2024-03-18T16:32:15.944730627Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:TriggerMode
2024-03-18T16:32:15.944732318Z         trigger_source: NotConnected:
2024-03-18T16:32:15.944734008Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:TriggerSource_RBV
2024-03-18T16:32:15.944735680Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:TriggerSource
2024-03-18T16:32:15.944737396Z         acquire: NotConnected:
2024-03-18T16:32:15.944739097Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:Acquire_RBV
2024-03-18T16:32:15.944740769Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:Acquire
2024-03-18T16:32:15.944742471Z         acquire_time: NotConnected:
2024-03-18T16:32:15.944744140Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:AcquireTime_RBV
2024-03-18T16:32:15.944745846Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:AcquireTime
2024-03-18T16:32:15.944747508Z         num_images: NotConnected:
2024-03-18T16:32:15.944749187Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:NumImages_RBV
2024-03-18T16:32:15.944750856Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:NumImages
2024-03-18T16:32:15.944752575Z         image_mode: NotConnected:
2024-03-18T16:32:15.944754263Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:ImageMode_RBV
2024-03-18T16:32:15.944755937Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:ImageMode
2024-03-18T16:32:15.944757614Z         array_counter: NotConnected:
2024-03-18T16:32:15.944759294Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:ArrayCounter_RBV
2024-03-18T16:32:15.944760958Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:DET:ArrayCounter
2024-03-18T16:32:15.944762618Z         array_size_x: NotConnected: ca://BL38P-DI-DCAM-03:DET:ArraySizeX_RBV
2024-03-18T16:32:15.944764294Z         array_size_y: NotConnected: ca://BL38P-DI-DCAM-03:DET:ArraySizeY_RBV
2024-03-18T16:32:15.944765977Z         detector_state: NotConnected: ca://BL38P-DI-DCAM-03:DET:DetectorState_RBV
2024-03-18T16:32:15.944767628Z         wait_for_plugins: NotConnected: ca://BL38P-DI-DCAM-03:DET:WaitForPlugins
2024-03-18T16:32:15.944771249Z         unique_id: NotConnected: ca://BL38P-DI-DCAM-03:DET:UniqueId_RBV
2024-03-18T16:32:15.944772960Z         nd_attributes_file: NotConnected: ca://BL38P-DI-DCAM-03:DET:NDAttributesFile
2024-03-18T16:32:15.944774669Z     hdf: NotConnected:
2024-03-18T16:32:15.944776341Z         position_mode: NotConnected:
2024-03-18T16:32:15.944778013Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:PositionMode_RBV
2024-03-18T16:32:15.944779687Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:PositionMode
2024-03-18T16:32:15.944781381Z         compression: NotConnected:
2024-03-18T16:32:15.944783098Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:Compression_RBV
2024-03-18T16:32:15.944784758Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:Compression
2024-03-18T16:32:15.944786420Z         num_extra_dims: NotConnected:
2024-03-18T16:32:15.944788101Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:NumExtraDims_RBV
2024-03-18T16:32:15.944789769Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:NumExtraDims
2024-03-18T16:32:15.944797026Z         file_path: NotConnected:
2024-03-18T16:32:15.944798835Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:FilePath_RBV
2024-03-18T16:32:15.944800509Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:FilePath
2024-03-18T16:32:15.944802187Z         file_name: NotConnected:
2024-03-18T16:32:15.944803896Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:FileName_RBV
2024-03-18T16:32:15.944805579Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:FileName
2024-03-18T16:32:15.944807246Z         file_path_exists: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:FilePathExists_RBV
2024-03-18T16:32:15.944808929Z         file_template: NotConnected:
2024-03-18T16:32:15.944810602Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:FileTemplate_RBV
2024-03-18T16:32:15.944812293Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:FileTemplate
2024-03-18T16:32:15.944813975Z         full_file_name: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:FullFileName_RBV
2024-03-18T16:32:15.944815644Z         file_write_mode: NotConnected:
2024-03-18T16:32:15.944817333Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:FileWriteMode_RBV
2024-03-18T16:32:15.944818985Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:FileWriteMode
2024-03-18T16:32:15.944820689Z         num_capture: NotConnected:
2024-03-18T16:32:15.944822358Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:NumCapture_RBV
2024-03-18T16:32:15.944824023Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:NumCapture
2024-03-18T16:32:15.944825734Z         num_captured: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:NumCaptured_RBV
2024-03-18T16:32:15.944827417Z         swmr_mode: NotConnected:
2024-03-18T16:32:15.944829085Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:SWMRMode_RBV
2024-03-18T16:32:15.944830751Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:SWMRMode
2024-03-18T16:32:15.944832430Z         lazy_open: NotConnected:
2024-03-18T16:32:15.944834141Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:LazyOpen_RBV
2024-03-18T16:32:15.944835806Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:LazyOpen
2024-03-18T16:32:15.944837503Z         capture: NotConnected:
2024-03-18T16:32:15.944839209Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:Capture_RBV
2024-03-18T16:32:15.944840878Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:Capture
2024-03-18T16:32:15.944844255Z         flush_now: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:FlushNow
2024-03-18T16:32:15.944845984Z         array_size0: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:ArraySize0_RBV
2024-03-18T16:32:15.944847671Z         array_size1: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:ArraySize1_RBV
2024-03-18T16:32:15.944849345Z         nd_array_port: NotConnected:
2024-03-18T16:32:15.944851025Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:NDArrayPort_RBV
2024-03-18T16:32:15.944853161Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:NDArrayPort
2024-03-18T16:32:15.944854888Z         enable_callback: NotConnected:
2024-03-18T16:32:15.944856614Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:EnableCallbacks_RBV
2024-03-18T16:32:15.944858343Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:EnableCallbacks
2024-03-18T16:32:15.944860046Z         nd_array_address: NotConnected:
2024-03-18T16:32:15.944861729Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:NDArrayAddress_RBV
2024-03-18T16:32:15.944863422Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:NDArrayAddress
2024-03-18T16:32:15.944865105Z         unique_id: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:UniqueId_RBV
2024-03-18T16:32:15.944866781Z         nd_attributes_file: NotConnected: ca://BL38P-DI-DCAM-03:HDF5:NDAttributesFile
2024-03-18T16:32:15.944868491Z     stats: NotConnected:
2024-03-18T16:32:15.944870181Z         nd_array_port: NotConnected:
2024-03-18T16:32:15.944871852Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:STAT:NDArrayPort_RBV
2024-03-18T16:32:15.944873525Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:STAT:NDArrayPort
2024-03-18T16:32:15.944875230Z         enable_callback: NotConnected:
2024-03-18T16:32:15.944876943Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:STAT:EnableCallbacks_RBV
2024-03-18T16:32:15.944878617Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:STAT:EnableCallbacks
2024-03-18T16:32:15.944880298Z         nd_array_address: NotConnected:
2024-03-18T16:32:15.944882020Z             read_pv: NotConnected: ca://BL38P-DI-DCAM-03:STAT:NDArrayAddress_RBV
2024-03-18T16:32:15.944883691Z             write_pv: NotConnected: ca://BL38P-DI-DCAM-03:STAT:NDArrayAddress
2024-03-18T16:32:15.944885374Z         unique_id: NotConnected: ca://BL38P-DI-DCAM-03:STAT:UniqueId_RBV
2024-03-18T16:32:15.944887055Z         nd_attributes_file: NotConnected: ca://BL38P-DI-DCAM-03:STAT:NDAttributesFile
2024-03-18T16:32:15.944888624Z 
2024-03-18T16:32:15.944890178Z 
2024-03-18T16:32:15.944891880Z ERROR:    Application startup failed. Exiting.
2024-03-18T16:32:16.233651586Z Exception ignored in: <function Pool.__del__ at 0x7f19039eb240>
2024-03-18T16:32:16.233666576Z Traceback (most recent call last):
2024-03-18T16:32:16.233668697Z   File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 271, in __del__
2024-03-18T16:32:16.233674811Z     self._change_notifier.put(None)
2024-03-18T16:32:16.233774484Z   File "/usr/local/lib/python3.11/multiprocessing/queues.py", line 377, in put
2024-03-18T16:32:16.233803082Z     self._writer.send_bytes(obj)
2024-03-18T16:32:16.233818146Z   File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 200, in send_bytes
2024-03-18T16:32:16.233883675Z     self._send_bytes(m[offset:offset + size])
2024-03-18T16:32:16.233911004Z   File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 427, in _send_bytes
2024-03-18T16:32:16.233991810Z     self._send(header + buf)
2024-03-18T16:32:16.234004008Z   File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 384, in _send
2024-03-18T16:32:16.234081555Z     n = write(self._handle, buf)
2024-03-18T16:32:16.234106655Z         ^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-18T16:32:16.234110125Z OSError: [Errno 9] Bad file descriptor

**Comment by callumforrester** [comment]
Tests are now passing

**Review by DominicOram — APPROVED** [review]
Tested by running the system tests against i03 and got the following error:
```
(.venv) [ffv81422@ws455 dodal]$ python tests/system_tests/test_i03_system.py 
Making all i03 devices
Traceback (most recent call last):
  File "/scratch/ffv81422/hyperion/dodal/tests/system_tests/test_i03_system.py", line 22, in <module>
    make_all_devices(i03)
  File "/scratch/ffv81422/hyperion/dodal/src/dodal/utils.py", line 130, in make_all_devices
    devices: dict[str, AnyDevice] = invoke_factories(factories, **kwargs)
  File "/scratch/ffv81422/hyperion/dodal/src/dodal/utils.py", line 155, in invoke_factories
    devices[dependent_name] = factories[dependent_name](**params, **kwargs)
  File "/scratch/ffv81422/hyperion/dodal/src/dodal/beamlines/i03.py", line 370, in panda
    return device_instantiation(
  File "/scratch/ffv81422/hyperion/dodal/src/dodal/utils.py", line 103, in wrapper
    return func(*args, **kwds)
  File "/scratch/ffv81422/hyperion/dodal/src/dodal/beamlines/beamline_utils.py", line 114, in device_instantiation
    _wait_for_connection(device_instance, sim=fake)
  File "/scratch/ffv81422/hyperion/dodal/src/dodal/beamlines/beamline_utils.py", line 54, in _wait_for_connection
    call_in_bluesky_event_loop(
  File "/scratch/ffv81422/hyperion/hyperion/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 2782, in call_in_bluesky_event_loop
    return fut.result(timeout=timeout)
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/scratch/ffv81422/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd_async/core/utils.py", line 99, in wait_for_connection
    raise NotConnected(exceptions)
ophyd_async.core.utils.NotConnected: 
coros: NotConnected: pva://BL03I-EA-PANDA-01PVI
```
This is expected as there's no PVA gateway for these. Error is a lot better as it actually gives us a PV name. Thanks @DiamondJoseph and @callumforrester

**Pull request merged**
