### PR TITLE
(DiamondLightSource/mx-bluesky#475) Method to allow access to full zocalo results

### PR DESCRIPTION
**Pull request by rtuck99**
Extends ZocaloResults to get access to everything instead of just the position and bounding box

Fixes DiamondLightSource/mx-bluesky#475

### CODE REVIEW

**Review by DominicOram — CHANGES_REQUESTED** [review]
The consensus in `ophyd_async` is to move away from arbitrary types on signals. I have made https://github.com/bluesky/ophyd-async/issues/601 to actually try and advertise this fact. We should probably refactor this to use individual signals rather than `XRCResults`, like we did for https://github.com/DiamondLightSource/dodal/pull/769.

Additionally, I think after this PR `get_processing_result` is no longer used, can we remove it?

**Review by dperl-dls — APPROVED** [review]
Looks good, approving, not merging until https://github.com/DiamondLightSource/mx-bluesky/pull/553 is ready

**Comment by rtuck99** [comment]
This PR now obsoleted by #858

**Comment by DominicOram** [comment]
With https://github.com/DiamondLightSource/dodal/pull/858 merged I think this is now redundant so closing

**Pull request closed without merging**
