### PR TITLE
add license check

### LINKED ISSUE #825: Add a github action for licensing compliance checker (testing for the python-copier-template purposes)
To prevent using libraries in our projects that are not compatible with our project licenses. For instance using a library with a more restrictive license in our library with a more permissive license. The likelihood of legal action for many of those libraries might not be that great, but multiplied by many libraries and time might be costly, at least in the developer time to migrate to a compatible alternative

https://github.com/marketplace/actions/dependencies-license-compliance-checker

See this

https://github.com/DiamondLightSource/python-copier-template/pull/199/files

### PR DESCRIPTION
**Pull request by stan-dot**
Fixes #825 

package used initially:
- https://github.com/pilosus/action-pip-license-checker

### CODE REVIEW

**Comment by DiamondJoseph** [comment]
This is only run on release- shouldn't we be checking during the PR to add the dependency?

**Comment by stan-dot** [comment]
good question @DiamondJoseph 

I'd say yes the footwork should be done beforehand. The license check in the release is more just for a sanity check, it does not need to happen at the early stage.

two layers > one

**Comment by DiamondJoseph** [comment]
What I mean @stan-dot is that this action should be run during the PR, not that it should be part of the review process. If we add a dependency that is not licensed, then we make use of it it'll be difficult to extract after the fact. I'd expect this PR to have triggered a new check so that we could see that we are not already non-compliant.

**Comment by stan-dot** [comment]
fair enough @DiamondJoseph , where exactly do you consider it is best to run it then? before the lint? after the test?

**Comment by DiamondJoseph** [comment]
It's independent of those, it's just another workflow to be run. Make it a new `_license.yml` in `.github/workflows` and add it to run alongside lint and test in `ci.yml`

**Comment by coretl** [comment]
This doesn't appear to be working, there is no license.json uploaded...

**Comment by DiamondJoseph** [comment]
image

**Comment by stan-dot** [comment]
looking into it

**Comment by stan-dot** [comment]
the package isn't that great.

maybe this is not a fire to put out https://swizec.com/blog/let-small-fires-burn/

**Comment by stan-dot** [comment]
not on critical path now, unassigning

**Comment by DiamondJoseph** [comment]
I think if we're breaking the law and using packages we are not allowed to, that's a pretty big fire. 
I'm back in the office this week if you want a 2nd pair of eyes to look at it, or I can make a ticket for myself to investigate other packages/tools.

**Comment by stan-dot** [comment]
other possible packages
- https://github.com/raimon49/pip-licenses
- https://github.com/graphcore/license-checker
- https://github.com/dhatim/python-license-check

**Comment by stan-dot** [comment]
this PR no longer relevant, comment in the issue - which would need to be solved in a different way

**Pull request closed without merging**
