### PR TITLE
Add a link to the make-new-ophyd-device chart doc

### PR DESCRIPTION
**Pull request by stan-dot**
Fixes #ISSUE

### Instructions to reviewer on how to test:
1. Do thing x
2. Confirm thing y happens

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://github.com/DiamondLightSource/dodal/wiki/Device-Standards)
- [ ] If changing the API for a pre-existing device, ensure that any beamlines using this device have updated their Bluesky plans accordingly
- [ ] Have the connection tests for the relevant beamline(s) been run via `dodal connect ${BEAMLINE}`

### CODE REVIEW

**Comment by callumforrester** [comment]
@stan-dot unsure why this makes the build fail or why it passed in the first place :)

**Comment by DiamondJoseph** [comment]
>  WARNING: toctree contains reference to nonexisting document 'developer/how-to/make-new-ophyd-async-device'

Probably needs to nix `developer`?

**Comment by stan-dot** [comment]
it's about md vs rst. on it now

**Comment by DiamondJoseph** [comment]
I would guess that you need `sphinxcontrib-mermaid` in the dependencies section of the pyproject.toml too.

**Comment by stan-dot** [comment]
I added it there!

**Comment by DiamondJoseph** [comment]
https://github.com/DiamondLightSource/dodal/blob/main/docs/conf.py#L32

Looks like it needs to be added to `docs/conf.py` too

**Review by callumforrester — APPROVED** [review]

**Pull request merged**
