### PR TITLE
fix flaky test in test_bart_robot.py

### PR DESCRIPTION
**Pull request by arikaran-13**
#943 Fix flakey bart robot unit test

### Instructions to reviewer on how to test:
1. Run the test tests/devices/unit_tests/test_bart_robot.py::test_given_program_not_running_and_pin_unmounts_then_mounts_when_load_pin_then_pin_loaded
2. Confirm that the test passes consistently, even if run multiple times.

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://diamondlightsource.github.io/dodal/main/reference/device-standards.html)
- [ ] If changing the API for a pre-existing device, ensure that any beamlines using this device have updated their Bluesky plans accordingly
- [ ] Have the connection tests for the relevant beamline(s) been run via `dodal connect ${BEAMLINE}`

### CODE REVIEW

**Review by olliesilvester — CHANGES_REQUESTED** [review]
I don't think these extra statements guarantee that the task will have finished in time - if we change the sleep times then the tests still fail.

A good short term the solution would just be to increase `await sleep(0.01)` slightly, and to increase `device.LOAD_TIMEOUT = 0.03` to account for this.

**Comment by arikaran-13** [comment]
> I don't think these extra statements guarantee that the task will have finished in time - if we change the sleep times then the tests still fail.
> 
> A good short term the solution would just be to increase `await sleep(0.01)` slightly, and to increase `device.LOAD_TIMEOUT = 0.03` to account for this.

I thought that since we are changing the state from PIN_MOUNTED to NO_PIN_MOUNTED and then back to PIN_MOUNTED, if we await the state change, the trigger() method will be called correctly. But if that doesn't fix the test, as a short-term solution, I have updated the timing of the LOAD_TIMEOUT

**Review by olliesilvester — APPROVED** [review]
Thanks!

**Comment by arikaran-13** [comment]
> Thanks!

Thanks you
This is my first open source contribution :)

**Pull request merged**
