### PR TITLE
Add some tests for status chaining util

### PR DESCRIPTION
**Pull request by dperl-dls**
Doesn't fix ~~Fixes~~ [Hyperion #1096](https://github.com/DiamondLightSource/hyperion/issues/1096)

doesn't replace ~~Replaces~~ `lambda`s with `partial` or other functions to ensure they are not called in the staging process.

adds some tests

### Instructions to reviewer on how to test:
1. Confirm old tests aren't broken
2. Confirm new tests make sense

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://github.com/DiamondLightSource/dodal/wiki/Device-Standards)

### CODE REVIEW

**Review by DominicOram — CHANGES_REQUESTED** [review]
I love the new tests but are you sure this fixes it? Running the same tests against the eiger in main passes fine

**Comment by dperl-dls** [comment]
Oh :( Should have thought to check whether lambdas of functions actually execute them first

**Review by DominicOram — CHANGES_REQUESTED** [review]
As discussed, given this didn't fix the issue can we change it back to lambdas but keep the tests. Then we'll merge this as it improves the codebase. But keep the original issue open as it doesn't fix it.

**Review by DominicOram — APPROVED** [review]
Looks good, even if didn't fix the issue

**Pull request merged**
